---

batch_size: 4

dataset: "cifar_mnist"

root_dir: "/data1/kikemura/IMG2GRAPH_Segmentation_Experiment"

experiment_name: "experiment-3"

model_save_dir: "saved_weights"

result_save_dir: "results"

val_image_size: [73, 73]

train_image_size: [73, 73]

graph_gen_model: "scg-net"

print_freq: 10

save_freq: 20

val_freq: 6

device: "cuda"

num_nodes: [70, 70]

learning_rate: 0.0016

save_pred: true

gnn: "agnn"